### ISSUE TITLE
i am using Magento with Redis , can i still use this

### ISSUE THREAD

**Issue by myselfgaurav** [Genaker/CloudFlare_FPC_Worker#2]
i am using Magento with Redis , can i still use this to speed up my website or will it cause any conflict , please gudie ,

**Comment by Genaker** [comment]
First of all, check the Fast FPC extension. Yes, it can improve the
performance of the Redis built-in FPC, file-based FPC, Varnish, or Magento
without chance at all!

**Comment by myselfgaurav** [comment]
one more query - as i an using Apache Webserver will it still be usefull to me

**Comment by Genaker** [comment]
Yes, of course! You must use it to protect it from the traffic, especially
with the Apache!
